name: Docker Image Build

on:
  pull_request:
***REMOVED***branches:
***REMOVED***- main

jobs:

  build:

***REMOVED***runs-on: ubuntu-latest

***REMOVED***steps:
***REMOVED***- uses: actions/checkout@v3
***REMOVED***- name: Build the Docker image
***REMOVED***  run:***REMOVED*** 
***REMOVED***docker build . --file WebApp.Dockerfile --tag sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER
***REMOVED***  
