name: Docker Image Publish

on:
  push:
***REMOVED***branches:
***REMOVED***- main

jobs:

  build:

***REMOVED***runs-on: ubuntu-latest

***REMOVED***steps:
***REMOVED***- name: Azure Container Registry Login
***REMOVED***  uses: Azure/docker-login@v2
***REMOVED***  with:
***REMOVED***# Container registry username
***REMOVED***username: ${{ secrets.SAMPLEAPP_ACR_USERNAME }}
***REMOVED***# Container registry password
***REMOVED***password: ${{ secrets.SAMPLEAPP_ACR_PASSWORD }}
***REMOVED***# Container registry server url
***REMOVED***login-server: sampleappaoaichatgpt.azurecr.io
***REMOVED***
***REMOVED***- uses: actions/checkout@v3
***REMOVED***- name: Build the Docker image
***REMOVED***  run:***REMOVED*** 
***REMOVED***docker build . --file WebApp.Dockerfile --tag sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
***REMOVED***docker tag sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:latest;
***REMOVED***docker push sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
***REMOVED***docker push sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:latest;
***REMOVED***  
