# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - oyd-vnet-webapp

on:
  push:
***REMOVED***branches:
***REMOVED***  - main
  workflow_dispatch:

jobs:
  build:
***REMOVED***runs-on: ubuntu-latest

***REMOVED***steps:
***REMOVED***  - uses: actions/checkout@v4

***REMOVED***  - name: Set up Python version
***REMOVED***uses: actions/setup-python@v5
***REMOVED***with:
***REMOVED***  python-version: '3.11'

***REMOVED***  - name: Create and start virtual environment
***REMOVED***run: |
***REMOVED***  python -m venv venv
***REMOVED***  source venv/bin/activate
***REMOVED***  
***REMOVED***  - name: Install dependencies
***REMOVED***run: pip install -r requirements.txt
***REMOVED***
***REMOVED***  # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

***REMOVED***  - name: Zip artifact for deployment
***REMOVED***run: zip release.zip ./* -r

***REMOVED***  - name: Upload artifact for deployment jobs
***REMOVED***uses: actions/upload-artifact@v4
***REMOVED***with:
***REMOVED***  name: python-app
***REMOVED***  path: |
***REMOVED******REMOVED***release.zip
***REMOVED******REMOVED***!venv/

  deploy:
***REMOVED***runs-on: ubuntu-latest
***REMOVED***needs: build
***REMOVED***environment:
***REMOVED***  name: 'Production'
***REMOVED***  url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
***REMOVED***permissions:
***REMOVED***  id-token: write #This is required for requesting the JWT

***REMOVED***steps:
***REMOVED***  - name: Download artifact from build job
***REMOVED***uses: actions/download-artifact@v4
***REMOVED***with:
***REMOVED***  name: python-app

***REMOVED***  - name: Unzip artifact for deployment
***REMOVED***run: unzip release.zip

***REMOVED***  
***REMOVED***  - name: Login to Azure
***REMOVED***uses: azure/login@v2
***REMOVED***with:
***REMOVED***  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6CEBDF3323824DD6B09104058717CBBE }}
***REMOVED***  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03F53410633A4BFCBC7CE37F3137C89E }}
***REMOVED***  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A06A418034794EFB81E546A61BF9D1C4 }}

***REMOVED***  - name: 'Deploy to Azure Web App'
***REMOVED***uses: azure/webapps-deploy@v3
***REMOVED***id: deploy-to-webapp
***REMOVED***with:
***REMOVED***  app-name: 'oyd-vnet-webapp'
***REMOVED***  slot-name: 'Production'
***REMOVED***  