# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Frontend

on:
  push:
***REMOVED***branches: [ "main" ]
  pull_request:
***REMOVED***branches: [ "main" ]
***REMOVED***

jobs:
  build:
***REMOVED***runs-on: ubuntu-latest
***REMOVED***defaults:
***REMOVED***  run:
***REMOVED***working-directory: frontend
***REMOVED***strategy:
***REMOVED***  matrix:
***REMOVED***node-version: [14.x, 16.x, 18.x, 21.x]
***REMOVED***# See supported Node.js release schedule at https://nodejs.org/en/about/releases/

***REMOVED***steps:
***REMOVED***- uses: actions/checkout@v3
***REMOVED***- name: Use Node.js ${{ matrix.node-version }}
***REMOVED***  uses: actions/setup-node@v3
***REMOVED***  with:
***REMOVED***node-version: ${{ matrix.node-version }}
***REMOVED***cache: 'npm'
***REMOVED***cache-dependency-path: '**/package-lock.json'
***REMOVED***- run: npm ci
***REMOVED***- run: npm run build --if-present
***REMOVED***# - run: npm test
