# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
***REMOVED***branches: [ "main" ]
  pull_request:
***REMOVED***branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_linux:
***REMOVED***runs-on:
***REMOVED***- ubuntu-latest
***REMOVED***steps:
***REMOVED***- uses: actions/checkout@v3
***REMOVED***- name: Set up Python 3.11
***REMOVED***  uses: actions/setup-python@v3
***REMOVED***  with:
***REMOVED***python-version: "3.11"
***REMOVED***- name: Install dependencies
***REMOVED***  run: |
***REMOVED***python -m pip install --upgrade pip
***REMOVED***pip install -r requirements-dev.txt
***REMOVED***- name: Test with pytest
***REMOVED***  run: |
***REMOVED***export PYTHONPATH=$(pwd)
***REMOVED***coverage run --omit=tests/integration_tests -m pytest -v --show-capture=stdout -k "not integration"
***REMOVED***coverage report -m
***REMOVED***coverage xml

***REMOVED***- name: Code Coverage Report
***REMOVED***  uses: irongut/CodeCoverageSummary@v1.3.0
***REMOVED***  with:
***REMOVED***filename: coverage.xml
***REMOVED***badge: true
***REMOVED***fail_below_min: true
***REMOVED***format: markdown
***REMOVED***hide_branch_rate: false
***REMOVED***hide_complexity: true
***REMOVED***indicators: true
***REMOVED***output: both
***REMOVED***thresholds: '60 80'

  test_windows:
***REMOVED***runs-on:
***REMOVED***- windows-latest
***REMOVED***steps:
***REMOVED***- uses: actions/checkout@v3
***REMOVED***- name: Set up Python 3.11
***REMOVED***  uses: actions/setup-python@v3
***REMOVED***  with:
***REMOVED***python-version: "3.11"
***REMOVED***- name: Install dependencies
***REMOVED***  run: |
***REMOVED***python -m pip install --upgrade pip
***REMOVED***pip install -r requirements-dev.txt
***REMOVED***- name: Test with pytest
***REMOVED***  run: |
***REMOVED***$env:PYTHONPATH=$pwd
***REMOVED***pytest -v --show-capture=stdout -k "not integration"
